# Spring Boot configuration
spring:
  application:
    name: banking
  # Database
  datasource:
    url: jdbc:postgresql://ec2-184-72-235-159.compute-1.amazonaws.com:5432/d2rlhn3ekcevr3?sslmode=require
    username: hibspswzsaatif
    password: 83aab305bfbc47043610b5482a1f61fb7df9884d2d244a69d5ae29f79922a9a9
    driverClassName: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: public
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: banking.hcmus@gmail.com
    password: banking123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
# Logger configuration
logging:
  level:
    org.springframework: DEBUG
    org.hibernate: INFO
# Server configuration
server:
  port: ${PORT:80}
  sessionTimeout: 30
# Security
banking:
  security:
    authentication:
      jwt:
        token-validity: 900
        token-validity-for-remember-me: 2592000
        token-refresh-validity: 86400
        base64-secret: NjUzNzc0YTkxZmU0YzAyYzVjODUyYTcwNDM4MzQ2OTQ=
    rsa:
      private-file: /keypair/private_key
      public-file: /keypair/public_key