# Spring Boot configuration
spring:
  application:
    name: banking
  # Database
  datasource:
    url: jdbc:postgresql://banking-postgres:5432/banking
    username: banking
    password: banking
    driverClassName: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: public
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: banking.hcmus@gmail.com
    password: banking123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
# Logger configuration
logging:
  level:
    org.springframework: DEBUG
    org.hibernate: INFO
# Server configuration
server:
  port: 8800
  sessionTimeout: 30
# Security
banking:
  security:
    authentication:
      jwt:
        token-validity: 900
        token-validity-for-remember-me: 2592000
        token-refresh-validity: 86400
        base64-secret: NjUzNzc0YTkxZmU0YzAyYzVjODUyYTcwNDM4MzQ2OTQ=
    rsa:
      private-file: /keypair/private_key
      public-file: /keypair/public_key
merchant:
  pgp:
    account: /AnotherInternetbanking/InfoAccount
    transaction: /AnotherInternetbanking/TranferInternerAnotherBank
    secret-key: Nhom6
  rsa:
    account: http://t2trc-ws.us-east-2.elasticbeanstalk.com/v1.0/account
    transaction: http://t2trc-ws.us-east-2.elasticbeanstalk.com/v1.0/transaction
    secret-key: 2177e8c6efca038fb79a7a5db257de98
    client-id: 2c9180827217cb57017218e755260002
    token: $2a$10$Uy1dFgxiObvyeUVQmwt8seqYPbGXBfPaE4XhhvesmWklNllhQUdye